### ISSUE TITLE
Does not render correctly on OS X

### ISSUE THREAD

**Issue by eliheuer** [mfeq/Qglif#2] opened 2020-09-01 04:33 UTC
I just tested commit 9b1c006 on Arch with Nightly and it worked without issues.

However, on macOS 10.15 I get a series of errors. It would be nice if this worked well on macOS and I'm happy to be a macOS tester for this editor.

The first error I get reads:
```Rust
error[E0599]: no function or associated item named `from_u32` found for type `char` in the current scope
   --> src/glifparser.rs:203:23
    |
203 |                 char::from_u32(u32::from_str_radix(unicodehex, 16).expect("<unicode> hex not int"))
    |                       ^^^^^^^^ function or associated item not found in `char`
    |
help: you are looking for the module in `std`, not the primitive type
    |
203 |                 std::char::from_u32(u32::from_str_radix(unicodehex, 16).expect("<unicode> hex not int"))
    |                 ^^^^^^^^^^^^^^^^^^^
```
I fixed this but got a few more errors and couldn't get it to build, I might try a PR to get it working, but thought I would post the issue first so you know I'm thinking about it.

Thanks!

**Comment by eliheuer** [comment] 2020-09-01 04:35
Arch screenshot:
![qglif-test](https://user-images.githubusercontent.com/5162664/91795163-c8561b80-ebd1-11ea-9090-babd4055c715.png)

**Comment by ctrlcctrlv** [comment] 2020-09-01 04:47
I just forced pushed for the last time and promise to not do it anymore; can you try on the force pushed branch?

**Comment by ctrlcctrlv** [comment] 2020-09-01 04:49
Nightly is required...I don't know why OS X isn't detecting that @eliheuer

**Comment by ctrlcctrlv** [comment] 2020-09-01 04:49
Unless for some reason the OS X nightly rustc cannot do `char::from_u32`??

**Comment by eliheuer** [comment] 2020-09-01 04:53
I just checked, I am and was using nightly on macOS.

**Comment by ctrlcctrlv** [comment] 2020-09-01 04:54
🤔 Hmm...

Please let me know if you figure it out; that is very strange. Or, if you can find an alternative for the function that doesn't need Nightly.

**Comment by ctrlcctrlv** [comment] 2020-09-01 04:55
I'm actively hacking on this right now to finally add the toolbox, as you saw on Twitter I converted all your icons into their own SVG.

https://github.com/mfeq/Qglif/commit/b740027edc0b7996fd5cc2c0dac838f095e46227#diff-3d350169560e75d0cf9fc8e3574a3639R6

So I hope I don't create a difficult merge conflict as I plan to refactor later probably

**Comment by eliheuer** [comment] 2020-09-02 05:18
This is what I get at commit `6271987`:
```
$ RUSTFLAGS=-Awarnings DEBUG=y RUST_BACKTRACE=1 cargo run -- Q_.glif

    Finished dev [unoptimized + debuginfo] target(s) in 0.70s
     Running `target/debug/Qglif Q_.glif`
Debug: Loaded "Q" (U+0051) from Q_.glif
called `Result::unwrap()` on an `Err` value: GlutinCreationError(NotSupported("could not open gl context"))
```

**Comment by eliheuer** [comment] 2020-09-02 05:19
I kinda like the idea of this not working on mac now that I think of it.

**Comment by ctrlcctrlv** [comment] 2020-09-02 09:57
I think that I'm requesting too high an OpenGL version for either Mac in general or your computer specifically.

**Comment by ctrlcctrlv** [comment] 2020-09-02 10:13
The internet says that Apple hates OpenGL and that's why it's not working. 🙃

I would need your expertise to figure out how to lower our version. They deprecated it apparently. I'm not dropping it though, let's be clear. Nothing else works on Linux well, and that's the most important platform for this, even above Windows.

**Comment by ctrlcctrlv** [comment] 2020-09-02 10:20
I think @kovidgoyal might know what I'm doing wrong also

**Comment by kovidgoyal** [comment] 2020-09-02 12:13
Without looking at the code, make sure you are requesting an OpenGL version no higher than 3.3, that's the last that reliably works on macOS

**Comment by ctrlcctrlv** [comment] 2020-09-02 12:23
I am:

https://github.com/mfeq/Qglif/blob/62719877eaa2ef511878f430d5071df62784876d/src/main.rs#L123

Although I am using multiple contexts... Perhaps the other context is using a higher version. I'll need to investigate when I get on the computer, but the hard thing is I can't test on Mac. Does anyone know of a service that will allow me to rent and remote in to a Mac? Like via VNC? Of course having graphics is a must.

**Comment by ctrlcctrlv** [comment] 2020-09-02 19:47
Update: It _does_ build.

![image](https://user-images.githubusercontent.com/838783/92029389-50473d00-ed1a-11ea-9f16-aa210cf93e6b.png)

I posted on Twitter I was looking to rent a Mac and got a few nice offers. In the meantime, this is the trial version of Macincloud. So it _does_ build.

I can't tell if this display problem is Macincloud's fault or not.

**Comment by ctrlcctrlv** [comment] 2020-09-03 23:25
Update: It really is broken. A nice guy on Twitter gave me TeamViewer access to his Mac. Debugging...

![image](https://user-images.githubusercontent.com/838783/92183034-0e91c180-ee02-11ea-8d3e-5ca986d5d62c.png)

**Comment by ctrlcctrlv** [comment] 2020-09-04 00:18
More confirmation: it is not a problem with VNC. l33tguy on Twitter built it on real hardware and got this.

I wonder if `rust-skia` works at all on Mac.

![image](https://user-images.githubusercontent.com/838783/92185718-7c8db700-ee09-11ea-8472-bdf2676e0034.png)

**Comment by milezzz** [comment] 2020-09-04 00:25
Above screenshot is from 10.15.2:

![mac](https://user-images.githubusercontent.com/2200225/92186084-da72cc80-ee12-11ea-9920-f42900c56c24.png)

**Comment by ctrlcctrlv** [comment] 2020-09-04 17:28
Update: I've tracked the problem down. The problem is in Reclutch. All its examples are broken on OS X in some way. I've informed @jazzfool, hopefully they can help as they already have with #1.

**Comment by ctrlcctrlv** [comment] 2020-09-08 17:32
Thanks everyone, @milezzz. #3 will close this. You're all welcome to try the branch early, but do note that you need to pull aclysma/skulpin to the parent directory as well if you do.

![image](https://user-images.githubusercontent.com/838783/92509122-9a1ea000-f1be-11ea-8ccf-a571bd3e7633.png)

**Closed** 2020-09-12 09:10 UTC
Labels: Should it?, enhancement
